Optimized Packs
immutable/platform-contracts pull request #85
Opened 2020-09-15 11:26 UTC by alex-connolly

2020-09-17 07:45 UTC, alonnovy requested changes
Hi Alex.  Looks good.... added a few questions/comments/stuff to think about.

2020-09-17 07:45 UTC, alonnovy commented on contracts/gods-unchained/contracts/s1/pack/optimized/OptimizedPack.sol
> +        uint256 randomness = uint256(keccak256(abi.encodePacked(_seed, address(this), _commitmentID)));
Would it save us some gas to calc the randomness in createCommitment and output it to log, where the cost is born by the (ETH) purchaser, so that it doesn't need to be repeated here where it costs us?

2020-09-17 07:47 UTC, alex-connolly commented on contracts/gods-unchained/contracts/s1/pack/optimized/OptimizedPack.sol
> +        uint256 randomness = uint256(keccak256(abi.encodePacked(_seed, address(this), _commitmentID)));
This is only called in an off-chain context, so there are no gas fees 😄

2020-09-18 00:12 UTC, alex-connolly commented on contracts/gods-unchained/contracts/s1/pack/optimized/OptimizedPack.sol
> +        bytes32 _seed,
Updated!

2020-09-18 00:22 UTC, alex-connolly commented on contracts/gods-unchained/contracts/s1/pack/optimized/OptimizedPack.sol
> +contract OptimizedPack is S1Vendor, RarityProvider {
I think this is a great idea! Previously, the requirement that `predictCards` be called by an on-chain operation made using a Strategy less desirable, as you require an external contract call (which has a gas penalty). However, with a fully off-chain `predictCards` this wouldn't matter - something to remember for next time!

2020-09-18 00:23 UTC, alex-connolly commented on contracts/gods-unchained/contracts/s1/pack/optimized/OptimizedPack.sol
> +    ) internal returns (uint256) {
Removed in latest commit.

2020-09-18 00:24 UTC, alex-connolly commented on contracts/gods-unchained/contracts/s1/pack/optimized/OptimizedPack.sol
> +            quantity: uint16(_quantity),
The `uint256` comes from the super contract `purchaseFor` function - we could impose the overflow check in the overriden `purchaseFor` or here in `_createCommitment`. It might make more sense to have it be in the higher-level function?

2020-09-18 00:29 UTC, alex-connolly commented on contracts/gods-unchained/contracts/s1/pack/optimized/OptimizedPack.sol
> +        emit CommitmentRecorded(commitmentID, commitment);
I reflected on this overnight - unfortunately it's not possible as the purchase transaction doesn't have access to the seed (hence the requirement for a callback!). We could possibly store the number of packs, but I'm not sure the increased cost makes sense.

2020-09-23 06:57 UTC, alonnovy commented on contracts/gods-unchained/contracts/s1/pack/optimized/OptimizedPack.sol
> +            quantity: uint16(_quantity),
Will the higher-level function be invoked, or will it be properly overidden?

2020-10-02 00:34 UTC, alex-connolly commented on contracts/gods-unchained/contracts/s1/pack/optimized/OptimizedPack.sol
> +            quantity: uint16(_quantity),
It will be invoked rather than overriden.

2020-10-02 03:44 UTC, merged